### ISSUE TITLE
make content/external_files filenames meaningful

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#119]
**Is your feature request related to a problem? Please describe.**
content/external_files hash names are not easy to follow

**Describe the solution you'd like**
make the filename based on the name of the google doc it came from.

### Examples:
<pre>
[horner@docs-qa ~/docs/content/external_files]$ ls -l 
-rw-r--r-- 1 horner mieremote  26745 Mar  2 01:38 00264f0ec0ad27a4850e9aa473591d25.png
-rw-r--r-- 1 horner mieremote  26606 Mar  2 01:38 003eeb61ad93147ffdabbcb4eec56939.png
-rw-r--r-- 1 horner mieremote   5286 Mar  2 01:38 004b0424be7aadfbaa6f25e6a883d64d.png
-rw-r--r-- 1 horner mieremote   8899 Mar  2 01:38 005543a950fcfd9da3711da44ddf7a79.png
-rw-r--r-- 1 horner mieremote  73745 Mar  2 01:38 0063f7899714766eef33975e804a509b.png
-rw-r--r-- 1 horner mieremote  13897 Mar  2 01:38 007c1cccc48f8aec9dda24f406a83807.png
-rw-r--r-- 1 horner mieremote  29967 Mar  2 01:38 008c9add918d08508b4634f6716e6674.png
-rw-r--r-- 1 horner mieremote   6344 Mar  2 01:38 009ca8307d11862e89ee136df3ca21f6.png
</pre>

**Comment by wreiske** [comment]
@horner I believe we did this on purpose, as these are hashes of the contents of the file. This allows the de-duplication of files across multiple google docs.
