### ISSUE TITLE
.navigation can get out of whack when there are multiple elements to a paragraph.

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#146]
../wikiGDrive/dist/main.js pull https://docs.google.com/document/d/1E0DKcCJjdeSPf_YjJUF7pMO72HzWYbsLw3cEmdGW5g0/edit

Adds a name: "Function" in the frontmatter instead of "Functions"

I Figured out that for some reason google was splitting the edit into two segments...  

      {
        "startIndex": 300,
        "endIndex": 316,
        "paragraph": {
          "elements": [
            {
              "startIndex": 300,
              "endIndex": 308,
              "textRun": {
                "content": "Function",
                "textStyle": {
                  "underline": true,
                  "foregroundColor": {
                    "color": {
                      "rgbColor": {
                        "red": 0.06666667,
                        "green": 0.33333334,
                        "blue": 0.8
                      }
                    }
                  },
                  "link": {
                    "url": "https://drive.google.com/open?id=1E0DKcCJjdeSPf_YjJUF7pMO72HzWYbsLw3cEmdGW5g0"
                  }
                }
              }
            },
            {
              "startIndex": 308,
              "endIndex": 316,
              "textRun": {
                "content": "s\n",
                "textStyle": {
                  "underline": true,
                  "foregroundColor": {

I fixed it by "Edit Link" and updating the title.  I wonder if we should warn when there are multiple elements in a paragraph node.  The code here https://github.com/mieweb/wikiGDrive/blob/86b6158a71fbfa7865f247c3067e4081761eccf8/src/generateNavigationHierarchy.ts#L34 assumes there is only a single element.  Would there be an easy way to return the content up to the '\n'?

**Comment by horner** [comment]
I added code to print a warning. https://github.com/mieweb/wikiGDrive/commit/69055f31ec7e99dd7169e29277f73f048c0fc142

**Comment by horner** [comment]
@ggodlewski Maybe I did not use the proper logger?  Should I use something other than console.log to stay proper?

**Comment by ggodlewski** [comment]
Do you have full JSON for such case? I'd like to create unit test for it.

**Comment by horner** [comment]
https://docs.google.com/document/d/1peKrRKiGqiRcjs9RckdjOOURNC5NUxTlzcTfv0xVv2s/edit
