### ISSUE TITLE
image links for embedded images are not correct

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#153]
This commit fixed the diagram, but made image links for embedded images strange (and a lot of diffs)
https://github.com/mieweb/wikiGDrive/commit/3ea4321acf113e99840f5d61d82b51413b96119a

See screenshot.
<img width="2272" alt="Screen Shot 2021-04-20 at 1 18 39 AM" src="https://user-images.githubusercontent.com/6094599/115341694-0c089000-a177-11eb-8acf-f77803a4b5cb.png">

**Comment by horner** [comment]
It looks like subsquent pulls are consistant, but the number is just odd.

**Comment by horner** [comment]
Also all of the files I checked the images are in the right order too.

**Comment by ggodlewski** [comment]
Check the `10fff_QiwKMY3vgw0nl4cTi8Jl3S6OUYQTsk-9gz17hE.zip`
Look for `<img>` inside html file. The order done by google seems to be random. 
That is why I added `extractHtmlImagesOrder` in https://github.com/mieweb/wikiGDrive/commit/3ea4321acf113e99840f5d61d82b51413b96119a
The other possibility is to generate new names for pngs while extracting them from the zip. But this would add additional complexity.

**Comment by horner** [comment]
It looks like this is working even tho the image names are strange.  I am going to close this issue.
