### ISSUE TITLE
watch is still not detecting changes

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#154]
I made a change and watch detected the first change... but then it refused to detect anymore changes.

I had to do a pull on the specific file to detect the change.

Please try testing.

Also, watch mode is too verbose.  I would like to see it scroll unless something is detected.
<img width="289" alt="Screen Shot 2021-04-20 at 1 41 44 AM" src="https://user-images.githubusercontent.com/6094599/115343265-a8cc2d00-a179-11eb-9742-a1a1fd4b9bed.png">

**Comment by ggodlewski** [comment]
The scroll bug was removed by recent PR.
Double check if you rebuilt the most recent `master`.

**Comment by horner** [comment]
yep.  The scrolling still happens on watch. It was fixed on pull.

**Comment by horner** [comment]
This was due to the git plugin errors scrolling the page.  Closing issue.
