### ISSUE TITLE
Markdown formatting does not work inside tables

### ISSUE THREAD

**Issue by wreiske** [mieweb/wikiGDrive#185]
**Describe the bug**
Markdown formatting does not work inside tables

https://docs.webchartnow.com/programs/ehr-certification/real-world-testing-plan-2021.html

**Expected behavior**
Formatting inside of tables should be respected, like bold text, hyperlinks, etc.

**Screenshots**
![Pasted File at December 1, 2021 8_23 PM](https://user-images.githubusercontent.com/6295044/144494531-2f7c7865-7a78-49c6-9874-211e7ae17551.png)

![Pasted File at December 1, 2021 8_24 PM](https://user-images.githubusercontent.com/6295044/144494534-74a46086-4c3b-45ce-87e3-08108c970843.png)

![image](https://user-images.githubusercontent.com/6295044/144494817-f18de756-d4e0-4b02-9f7b-002c37a6686f.png)

![image](https://user-images.githubusercontent.com/6295044/144494666-5cc670f6-1ac3-43dc-a8db-6048d8be052b.png)

**Versions:**
 - wikigdrive Version: https://github.com/mieweb/wikiGDrive/commit/d78f71887e5fe54e428e7950407a5ffd4defc00a

**Comment by horner** [comment]
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/6094599/162578304-e46d4f6a-beb8-4220-b250-10ad999a2dfa.png">
Fixed!
