### ISSUE TITLE
Make a DB FileIdtoPathMap

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#210]
FileIdtoPathMap {
  FileID
  Path
  Conflict_flag
}

### Terms
* Dir(ectory) = means the markdown directory (which are not allowed to conflict)
* Folder/Drive = Google Drive's idea of a Folder (which can have conflicts, cuz Google is crazy to allow this!)
* Document = the google drive content 
* File = the markdown file

This would map Google FileId for files AND directories.  It would be used to lookup URLs in Documents when they are edited to replace the URL with the actual Path in the markdown folder.

### Conflict Resolution
* If a Path exists already, a conflict has occurred.  A new Path should be calculated by starting at 1 and adding ++ until there is no conflict.  A conflict is a conflict, IF AND ONLY IF a Path already exists in the Markdown Dir (or Folder meta file) exists AND that Path is not a REDIRECT.  If it exists and it's a REDIRECT, then the contents can be replaced with the ned Document or Folder.
* If there is a file in the Markdown Dir (unknown to wikigdirve or Google Drive) it should still be considered a conflict.
* CheckConflict(FileId,Path) - Returns False if the FileId is unconflicted.  Returns True if there is going to be a conflict.
* GetUnConflictedPath(FilIid) - checks the 

### Document Rename
When a Document is renamed the Path is updated in the FileIdtoPathMap.  The old markdown file in the markdown folder is replaced with a redirect.md (with front matter that contains the FileId)  The content of the redirect.md should contain the local Path to the RENAMED Document.

### Folder Rename
When a Folder Rename is performed, all entires in the FileIdtoPathMap must be updated to their new Path. 
* Make a new Directory and recreate all of the contents of Folder in Dir
* Scan the old Dir, replacing each MDFile with a Redirect content (if it has the front matter)

**Comment by horner** [comment]
@ggodlewski Is this resolved now?

**Comment by horner** [comment]
This is a test:
https://github.com/mieweb/wikiGDrive/blob/19cab7e5d1e14a4f2fe1092e212279049f87dec9/.github/workflows/pull-request.yml#L52

We dont have a good way to test renaming a rename operation in production in a consistent way.  Doug to think on this.

**Comment by monpie3** [comment]
Since it is in the Done status, I'm closing the ticket.
