### ISSUE TITLE
Bold inside of tables are using the wrong markdown

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#213]
<img width="503" alt="Screen Shot 2022-03-07 at 2 49 01 PM" src="https://user-images.githubusercontent.com/6094599/157107541-e58a938f-420e-4ab5-96a3-e3f1c9c4f852.png">

**strong**

<pre>
`< strong >`
</pre>

**Comment by wreiske** [comment]
@horner duplicate of https://github.com/mieweb/wikiGDrive/issues/185

**Comment by horner** [comment]
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/6094599/162578267-c357813f-f245-4a99-b66e-c713d4b177ce.png">
Working
