### ISSUE TITLE
Fix HTML formatting- visible to clients

### ISSUE THREAD

**Issue by auhrick** [mieweb/wikiGDrive#226]
**Describe the bug**
HTML formatting displaying on client facing documentation 'Health Surveillance Playbook".

**To Reproduce**
1. Go to 'https://docs.enterprisehealth.com/functions/health-surveillance/health-surveillance-playbook.html'  online help to view what has been published for clients to view.
2. See page 12 of the googledoc (https://docs.google.com/document/d/1NCyrhUd_Qk586gaah_GvEGedpBOkizQteEtPsldw4C4/edit) to fix this. This is what it looks like client facing:
![Page12HSPlaybook](https://user-images.githubusercontent.com/102048851/159299578-1275872b-17e7-4aec-a7f6-238eaae51637.jpg)
3. Also see page 13-14 of the googledoc (https://docs.google.com/document/d/1NCyrhUd_Qk586gaah_GvEGedpBOkizQteEtPsldw4C4/edit) to fix. This is what is looks like client facing:
![Page12_14HSPlaybook](https://user-images.githubusercontent.com/102048851/159299926-d9c6c778-9074-4695-a0bd-3f7ff98ca079.jpg)
4.  Also, on page 1 of the document. Is there supposed to be a diagram that didn't come over from confluence, or was one never programmed and this was just a placeholder for one?
![Pg1HSPlaybook](https://user-images.githubusercontent.com/102048851/159366493-4716a5cb-42b8-498f-add3-5351bbfe1ddd.jpg)

**Expected behavior**
Please update the googledoc formatting so HTML is not visible and push out any updates to the document to the live online help.

**Comment by wreiske** [comment]
@ggodlewski this may already be fixed in some of your more recent #225 PRs. I just wanted to ping you to make sure.

**Comment by ggodlewski** [comment]
@wreiske there is a lots of updates in this PR. This can solve this issue. We need to merge it.

**Comment by horner** [comment]
We will come back and revisit this after I refactor the shared drive all of this documentation lives on. I'd like to do that next weekend.
