### ISSUE TITLE
Address security alert

### ISSUE THREAD

**Issue by thedigicraft** [mieweb/wikiGDrive#23]
There is a notice of a security issue on this repo.  Please look into and fix this if possible.  Let me know if there is an issue accessing the url below:

https://github.com/mieweb/wikiGDrive/network/alert/package-lock.json/serialize-javascript/open

**Comment by wreiske** [comment]
Duplicates: #19

**Comment by thedigicraft** [comment]
Thank you,  I missed your issue.
