### ISSUE TITLE
Look into google's watch api

### ISSUE THREAD

**Issue by wreiske** [mieweb/wikiGDrive#24]
Are we using this to watch for file changes?

https://developers.google.com/drive/api/v3/reference/changes/watch
https://developers.google.com/drive/api/v3/manage-changes

@ggodlewski @thedigicraft

**Comment by ggodlewski** [comment]
Nope. I can implement it. Just assign it to me.

**Comment by wreiske** [comment]
@ggodlewski you might want to discuss with @horner or @thedigicraft before starting work. Not sure what the priority for watching files will be.
