### ISSUE TITLE
Cloudflare caching CSS and forcing Safari to keep it in memory

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#253]
See screenshot below.
https://stackoverflow.com/questions/54326697/safari-caching-get-request-even-with-disabled-cache

Greg suggested he add the hash or /api/user?ts=18284 to the URL, but I wanted to make sure this was necessary before we did this.

**Comment by horner** [comment]
![image](https://user-images.githubusercontent.com/6094599/167262408-74de54ab-5798-413d-86f2-6a3655141461.png)

**Comment by horner** [comment]
@wreiske do you think we should add the url or fix cloudflare?

**Comment by wreiske** [comment]
@horner, IMO, best would be if you can change main.css to ${sha256('main.css')} like meteor. That way even when certain browsers ignore query strings, you'll always have the correct file.

**Comment by horner** [comment]
@wreiske thanks, I assigned this back to @ggodlewski
