### ISSUE TITLE
Google Drawings need to be exported as SVGs with clickable links

### ISSUE THREAD

**Issue by thedigicraft** [mieweb/wikiGDrive#27]
Google Drawings seem to be exporting as PNG's.  We need them to be SVGs with clickable content.  Example from the original test site, you can see where text was intended as links:  http://wikigrive.gitgis.com/example-folder/example-document.html#heading-3-a-diagram-with-links

**Comment by wreiske** [comment]
This has already been fixed in https://github.com/mieweb/wikiGDrive/issues/10

The test site probably needs updating.
