### ISSUE TITLE
File names need cleaned

### ISSUE THREAD

**Issue by thedigicraft** [mieweb/wikiGDrive#28]
I am finding some of the document names have characters such as `) ( : &` and this is causing issues with building the html.  We need the filenames to be cleaned of these characters and convert `&` to `and` The only valid characters would be: 
```
a-z
0-9
-
_  (underscore)
```
So, for example a document with this title: 

`Neat Page #1: My first (& only_page)` 

should be:

`neat-page-1-my-first-and-only_page.md`

**Comment by wreiske** [comment]
Probably should just slugify the file name?
