### ISSUE TITLE
Incorrect result

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#290]
FileId: 1TbYl56bYzCZsXjAtsF3wMay92vryJzpt7YrLOm22oyk
URL: https://wikigdrive.com/drive/0AF_nrE0_QH_2Uk9PVA/programs.md
Google Docs: https://drive.google.com/open?id=1TbYl56bYzCZsXjAtsF3wMay92vryJzpt7YrLOm22oyk

<img width="1348" alt="Screen Shot 2022-07-30 at 11 26 56 AM" src="https://user-images.githubusercontent.com/6094599/181923246-96063f82-2675-4f99-bab0-a699d5d5b2f6.png">

**Comment by ggodlewski** [comment]
Removing list.html seems to fix this issue
https://github.com/mieweb/docs/pull/1

**Comment by horner** [comment]
Looks good here: https://dev.wikigdrive.com/drive/0AF_nrE0_QH_2Uk9PVA/content/programs.md
