### ISSUE TITLE
Block port 80 on server/cloudflare

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#291]

**Comment by wreiske** [comment]
Everything has been moved to use Cloudflared tunnels & https is enforced on the cloudflare level.

**Comment by ggodlewski** [comment]
It seems it broke preview:
https://dev.wikigdrive.com/preview/0AF_nrE0_QH_2Uk9PVA/wc-eh-docs/

It used to show:
/var/www/preview-develop/0AF_nrE0_QH_2Uk9PVA/wc-eh-docs/index.html

**Comment by wreiske** [comment]
Ahh, was hoping to bypass nginx and talk directly to the port. If we are serving those files statically I'll have to fix that. 

I'll look at this today.

**Comment by wreiske** [comment]
@ggodlewski it's working now. https://dev.wikigdrive.com/preview/0AF_nrE0_QH_2Uk9PVA/wc-eh-docs/
