### ISSUE TITLE
Incorrect result - Bullets / Markdown inside tables

### ISSUE THREAD

**Issue by ggodlewski** [mieweb/wikiGDrive#295]
Fix "Current status of the Immunization event...."

FileId: 1pra9Trk_pf9pWs5HVMcFyq8rC3ubybUPZ0_Il2M3uoE
URL: https://dev.wikigdrive.com/drive/0AF_nrE0_QH_2Uk9PVA/resources/system-specifications/fhir-application-programming-interface-api/resource-specifications.md#markdown
Google Docs: https://drive.google.com/open?id=1pra9Trk_pf9pWs5HVMcFyq8rC3ubybUPZ0_Il2M3uoE

**Comment by wreiske** [comment]
![image](https://user-images.githubusercontent.com/6295044/184159561-59a085f7-563e-425a-860c-d6978a9494e5.png)
