### ISSUE TITLE
Incorrect Result - Page very broken

### ISSUE THREAD

**Issue by wreiske** [mieweb/wikiGDrive#304]
https://docs.enterprisehealth.com/functions/medication-management-and-e-prescribing/prescribing-adding-medications/

This entire page seems broken. Images aren't showing. The formatting is off. 🤔 

<img width="953" alt="Screen Shot 2022-08-30 at 9 20 58 AM" src="https://user-images.githubusercontent.com/6295044/187476210-761d09bb-99f6-4771-99c6-20f7d5461985.png">
<img width="984" alt="Screen Shot 2022-08-30 at 9 21 13 AM" src="https://user-images.githubusercontent.com/6295044/187476263-7aae0118-18d8-4641-b2d0-ba3223421d68.png">

**Comment by ggodlewski** [comment]
Images fixed

**Comment by wreiske** [comment]
This has been updated and resolved. Thanks
