### ISSUE TITLE
(Urgent) Incorrect Result - Links do not work on some pages

### ISSUE THREAD

**Issue by wreiske** [mieweb/wikiGDrive#305]
After a recent update, it seems that many links are linking to the .md files instead of the actual html. 

![image](https://user-images.githubusercontent.com/6295044/187536280-41589cf6-e664-4ac1-828f-5cc17ba03915.png)

Example:
https://dev.wikigdrive.com/drive/0AF_nrE0_QH_2Uk9PVA/content/rapid-deployment/review-sessions/review-session-patient-registration.md
https://docs.webchartnow.com/rapid-deployment/review-sessions/review-session-patient-registration/

![image](https://user-images.githubusercontent.com/6295044/187536887-cd9bab08-f59e-4465-8d14-a797fb970825.png)

Another example: https://docs.webchartnow.com/resources/system-specifications/application-programming-interface-api/

![image](https://user-images.githubusercontent.com/6295044/187538856-b779a608-ed69-45a2-8bc7-301abfdc4d61.png)

**Comment by ggodlewski** [comment]
You need to add render-link.html hook to the layouts:

https://gohugo.io/templates/render-hooks/

**Comment by wreiske** [comment]
The layouts are all generated from the wikigdrive markdown files in the `content` folder. 

The link for example shows:
```
[Terms of API Use](application-programming-interface-api/terms-of-api-use.md)
```

Shouldn't the wikigdrive link change that to just be 
```
[Terms of API Use](application-programming-interface-api/terms-of-api-use.html)
```

or something similar?

**Comment by wreiske** [comment]
Actually, I now know exactly what you mean. I fixed it. Thank you!
