### ISSUE TITLE
Make the creation of index.md an option

### ISSUE THREAD

**Issue by thedigicraft** [mieweb/wikiGDrive#31]
The index.md file that is being generated is causing problems because of how Hugo treats that file name.  We need a flag that enables this (make it disabled by default) and that flag should accept a desired filename (or index.md if left blank).

**Comment by ggodlewski** [comment]
I don't have any index.md in generated content directory and I cannot find any place in the code which generates such file. What options do you use?

**Comment by thedigicraft** [comment]
My apologies.  There is an item in the[ Project Document ](https://docs.google.com/document/d/1H6vwfQXIexdg4ldfaoPUjhOZPnSkNn6h29WD6Fi-SBY/edit#bookmark=id.an52jifjcfq0)  that states we need toc.md and index.md created.  So, I assumed that was why I was getting an index.md when running --without-folder-structure.  However, after reading your comment, I searched Google Drive and found that we actually have a document titled Index.  So I am closing this issue.
