### ISSUE TITLE
Incorrect Result - Links not working in bullets

### ISSUE THREAD

**Issue by wreiske** [mieweb/wikiGDrive#311]
https://docs.webchartnow.com/resources/system-specifications/on-premise-deployment/#managed-services
https://docs.google.com/document/d/1W32Q90BZqGacjJHvzQiKrDRBIvh47oBt5LK4gwHK5HI/edit

![image](https://user-images.githubusercontent.com/6295044/190239154-314189a2-8c17-40fe-83be-85e75f512e28.png)

**Comment by ggodlewski** [comment]
![image](https://user-images.githubusercontent.com/818238/197597805-a7f30d2a-8373-4c4b-a1e1-df03fd3f93ef.png)
