### ISSUE TITLE
Update verbiage for WikiDrive update

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#316]
<img width="995" alt="Screen Shot 2022-10-07 at 9 26 06 AM" src="https://user-images.githubusercontent.com/6094599/194564778-1164cb32-230f-49d7-92b3-92f859791b0f.png">

**Comment by ggodlewski** [comment]
![image](https://user-images.githubusercontent.com/818238/194702393-c6d8338a-5b2c-44fd-84a2-664f1ae8d03f.png)
