### ISSUE TITLE
UI landing screen

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#317]
<img width="1222" alt="Screen Shot 2022-10-07 at 9 43 45 AM" src="https://user-images.githubusercontent.com/6094599/194568283-0738cea9-639e-4c83-b0e3-33122bec1107.png">
See Screenshot

**Comment by ggodlewski** [comment]
![image](https://user-images.githubusercontent.com/818238/194702894-6b57c6cd-18d4-4b4d-87d1-b889bf606f9a.png)
