### ISSUE TITLE
git history does not allow wrapping in the log

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#318]
<img width="1180" alt="Screen Shot 2022-10-07 at 9 49 05 AM" src="https://user-images.githubusercontent.com/6094599/194569450-aee88e2f-85bd-498b-9a7a-2a939c501e35.png">

**Comment by ggodlewski** [comment]
![image](https://user-images.githubusercontent.com/818238/194700555-29e5c19d-9d97-4091-b354-a5af8e6dd92b.png)
