### ISSUE TITLE
Add edit link

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#321]
See diagram
<img width="1256" alt="Screen Shot 2022-10-08 at 10 58 55 AM" src="https://user-images.githubusercontent.com/6094599/194713865-18dfa135-02a1-4b98-816f-60e7cd54534e.png">

**Comment by ggodlewski** [comment]
![image](https://user-images.githubusercontent.com/818238/194884417-0b74e7b4-21f3-4989-8a24-3838ee94bb6b.png)
