### ISSUE TITLE
Explore ways to ignore version change that have no content or meta content changes.

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#322]
<img width="926" alt="Screen Shot 2022-10-08 at 11 02 21 AM" src="https://user-images.githubusercontent.com/6094599/194714056-7045ae35-293b-45cd-9694-3ba952a82ef4.png">

**Comment by ggodlewski** [comment]
Fixed in here https://github.com/mieweb/wikiGDrive/blob/develop/src/git/GitScanner.ts#L713
