### ISSUE TITLE
Watch is buggy

### ISSUE THREAD

**Issue by thedigicraft** [mieweb/wikiGDrive#33]
While using --without-folder-structure flag (and possibly without the flag) I am encountering two issues:

1.  Only documents in the root folder are being watched. We need all child folders being watched.
2. When making changes to files in root folder, not all changes are being caught. 
    - Sometimes if I make a change to a document, it is not caught, but if I open another, and make a change, then go back to the original document and make a new change it will be caught.

We need consistent behavior and for it to work in all child folders.  We will be using the watch feature trigger a new Hugo build on each change to allow content writers to preview their edits in a development version of the site.

**Comment by ggodlewski** [comment]
What do you mean by changing files in root folder? Are you changing them on local disk?
"--watch" flag looks for changes in the google drive.

**Comment by thedigicraft** [comment]
Yes, I am referring to Google Drive.  So, if you use the original example folder in Google Drive as a reference (see image below):  Bullet point 1 is referring to any document in "Test Folder" and bullet point 2 is referring to documents in the root folder; Example Document, sample conflict, Test Page, and sample conflict.

![image](https://user-images.githubusercontent.com/5841966/72468836-1554c100-37ac-11ea-9f7a-fc9117177b6b.png)
