### ISSUE TITLE
Missing image on index page

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#339]
This page is missing images! https://dev.wikigdrive.com/preview/0AF_nrE0_QH_2Uk9PVA/_manual/
<img width="1056" alt="Screenshot 2022-11-12 at 4 14 38 PM" src="https://user-images.githubusercontent.com/6094599/201494843-4dc28ad5-1352-44b0-ad89-edacdbda8e8c.png">

It looks like the image markdown add a "../" for every image other page (see example below) has the trailing slash.

FileId: 1C29_huh5LN64dXnkc7pHe_kgNH-dLYb5p8drt872IE0
URL: https://dev.wikigdrive.com/drive/0AF_nrE0_QH_2Uk9PVA/content/_index.md#html
Google Docs: https://drive.google.com/open?id=1C29_huh5LN64dXnkc7pHe_kgNH-dLYb5p8drt872IE0

### Other page example
https://dev.wikigdrive.com/preview/0AF_nrE0_QH_2Uk9PVA/_manual/programs/compliance-programs/medical-surveillance-program/

because it ends in a slash

FileId: 161HYbm5aR9SRHIzLUExrLxy-5oT0_OEABIdSSsRPVLg
URL: https://dev.wikigdrive.com/drive/0AF_nrE0_QH_2Uk9PVA/content/programs/compliance-programs/medical-surveillance-program.md#html
Google Docs: https://drive.google.com/open?id=161HYbm5aR9SRHIzLUExrLxy-5oT0_OEABIdSSsRPVLg

**Comment by horner** [comment]
I think the bug was introduced here: https://github.com/mieweb/wikiGDrive/commit/87d92855cadb87b5b2c3c3d8228444ca8f02c759

this looks like dead code?
https://github.com/mieweb/wikiGDrive/blob/38763d0f1ef5cae747825e9039d3aba463f29626/src/odt/OdtToMarkdown.ts#L320

**Comment by ggodlewski** [comment]
Fixed with 683f3a7802e7cd6d7988688f54414b9ae391f1e8
