### ISSUE TITLE
Special Redirects should be light grey and be removable

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#365]
<img width="761" alt="Screenshot 2023-01-22 at 7 04 06 PM" src="https://user-images.githubusercontent.com/6094599/213947864-a115a2b6-951c-419e-bcdc-b12b9b37083b.png">

**Comment by ggodlewski** [comment]
![image](https://user-images.githubusercontent.com/818238/215279737-4a829f5f-a4fd-45ca-acd0-10ea8669dc88.png)
