### ISSUE TITLE
PDFs are not copied out to the drive

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#367]
You'll notice in this folder there is a PDF.

https://drive.google.com/drive/folders/1uYzQROxAcRAaC5tUMD8kTo8w9N1Lh3zh

In this document, there is a link to the PDF https://docs.google.com/document/d/181WNaOF2YKqpFmbb4SSXEOUxGi4vdCfN6xyCaYV7S3s/edit

But you'll notice the URL and file is left on google drive and not copied into the folder.  Should we copy PDF like other images?

some companies block anything coming from drive.google.com it would be nice to have the option.  If the url is to a file in the shared drive, I think we should copy and fix the url to point to the version in content folder.

**Comment by ggodlewski** [comment]
![image](https://user-images.githubusercontent.com/818238/226199691-06d71003-bab2-4874-bf5e-bc08e04cf11d.png)
