### ISSUE TITLE
Git status screen

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#370]
<img width="1174" alt="Screenshot 2023-03-18 at 2 30 28 PM" src="https://user-images.githubusercontent.com/6094599/226129110-eadad5d7-1070-4592-a67d-317fba0497ce.png">

**Comment by ggodlewski** [comment]
![image](https://user-images.githubusercontent.com/818238/226383491-fdd559bb-1fa7-423c-8a6c-323f8b98c353.png)
