### ISSUE TITLE
GIT push failed

### ISSUE THREAD

**Issue by auhrick** [mieweb/wikiGDrive#402]
I'm not able to commit documentation updates.

When I enter a commit message and click the Commit & Push button, I get the following message "Git push failed"
![image](https://github.com/mieweb/wikiGDrive/assets/102048851/949fab98-bd23-46e5-92ca-7ddacdf2eaee)
![image](https://github.com/mieweb/wikiGDrive/assets/102048851/56197b66-e48f-4f86-b15c-57e49aa1648c)

URL to log error message: https://wikigdrive.com/drive/0AF_nrE0_QH_2Uk9PVA#drive_logs:job-c97ee681-9368-4906-934b-e798fa760dac 

I attempted a second document, but got the same results.
![image](https://github.com/mieweb/wikiGDrive/assets/102048851/92190960-ac1e-4336-8376-3ecf1b1b3366)
![image](https://github.com/mieweb/wikiGDrive/assets/102048851/8065757d-0b6e-4c59-b2d6-1838e96d1f34)
![image](https://github.com/mieweb/wikiGDrive/assets/102048851/ad05cdbc-19ec-4d4a-8b06-8a18104613c2)

URL to log error message: https://wikigdrive.com/drive/0AF_nrE0_QH_2Uk9PVA#drive_logs:job-b2e04504-d1e6-466f-9de2-21affee58847

**Comment by anichols27** [comment]
Same for me.
Brand new help guide trying to commit: https://docs.google.com/document/d/16XgocUDbGRvTr8qroJOXucpx0JFi7zBud5e2fsv9jmM/edit#heading=h.oomy3xxba9lw
I **DID** successfully commit the navigation page, but then when trying to commit this brand new help guide, I get a fail also.
![11-20e](https://github.com/mieweb/wikiGDrive/assets/137406473/70f4e04d-4b5b-4b16-8640-bb943156c840)

**Comment by ggodlewski** [comment]
@wreiske can you have a look:

There is problem with document: https://wikigdrive.com/drive/0AF_nrE0_QH_2Uk9PVA/content/functions/reports/health-surveillance-reports.md#markdown
The preview is present: https://wikigdrive.com/preview/0AF_nrE0_QH_2Uk9PVA/_manual/functions/reports/health-surveillance-reports/
The file is commited to gitub and present in latest release: https://github.com/mieweb/docs/compare/11-20-2023_1548...master
The build action was executed: https://github.com/mieweb/docs/actions/runs/6935701392/job/18866380027

But. It doesn't work here: https://docs.enterprisehealth.com/functions/reports/health-surveillance-reports
