### ISSUE TITLE
Unable to publish documentation-"Action failed" 

### ISSUE THREAD

**Issue by auhrick** [mieweb/wikiGDrive#408]
Issue:

I'm trying to publish "Chart Data CSV API"  https://docs.google.com/document/d/1Jv5jf4al_rY2ZMYQmBYEW-DWpyJudarkxKZ8sbg_uSs/edit and am getting a Action Failed message.

![image](https://github.com/mieweb/wikiGDrive/assets/102048851/0ea773c8-95fd-49c1-b0c6-3e4c82b522ea)

URL to log: https://wikigdrive.com/drive/0AF_nrE0_QH_2Uk9PVA#drive_logs:job-5d9607e0-d3e0-43b3-82ef-e000da111ab0 

Screenshot of log:

![image](https://github.com/mieweb/wikiGDrive/assets/102048851/03df52f4-871a-4124-b222-c5e608db257a)
![image](https://github.com/mieweb/wikiGDrive/assets/102048851/2f2446a1-aabc-4d68-bc77-1c0c395a7298)

**Comment by ggodlewski** [comment]
@wreiske I'm unable to log into server (sent you message on upwork).

There is a missing docker image: https://github.com/mieweb/wikiGDrive/blob/master/.github/workflows/ProdServerDeploy.yml#L47

**Comment by wreiske** [comment]
@ggodlewski sent info on upwork, server should be accessible to you now.
