### ISSUE TITLE
Still unable to publish

### ISSUE THREAD

**Issue by auhrick** [mieweb/wikiGDrive#410]
I am still unable to publish.

![image](https://github.com/mieweb/wikiGDrive/assets/102048851/2a478e3c-a358-4427-88ec-3ff6215e5833)
![image](https://github.com/mieweb/wikiGDrive/assets/102048851/1fc40cbd-c16e-4cd9-9bb4-78ac80ec1c07)
![image](https://github.com/mieweb/wikiGDrive/assets/102048851/8d9871da-b24c-4d36-a21c-2a6f71f72e20)
![image](https://github.com/mieweb/wikiGDrive/assets/102048851/a6875ba8-c633-4581-a1e6-ccaf01be4bb5)

**Comment by ggodlewski** [comment]
@horner can you help with that? Will wrote that he's unavailable this week.
Lots of "Permission denied (13)"
https://github.com/mieweb/docs/actions/runs/7529647741/job/20494299524

**Comment by hammbi** [comment]
Tested publishing documentation today and the changes pushed successfully to QA and PROD. Asking Alice to test and close this ticket.
