### ISSUE TITLE
Investigate support for the new code blocks (and other @ operations)

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#412]
https://support.google.com/docs/answer/11276813?hl=en&ref_topic=9045752&sjid=7580833052529989676-NC

Specifically code blocks:

https://duncanlew.medium.com/easily-format-and-highlight-your-code-in-google-docs-c51cbc0ce430

**Comment by ggodlewski** [comment]
Test doc: https://docs.google.com/document/d/15OQiVlYvk4WIWHJeB3Ow8-hDH0MxqR8K-zkwbQtWcBY/edit

**Comment by horner** [comment]
No indication of language in the code block!  Damn you google!

So for now we will just make sure they are 
```
peformatted txt
```
