### ISSUE TITLE
Add a visual indicator to show how far behind git is from the upstream

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#419]
<img width="1332" alt="Screenshot 2024-01-21 at 1 21 30 PM" src="https://github.com/mieweb/wikiGDrive/assets/6094599/f40351db-4e85-48bd-ba76-a2347c08e8dd">

**Comment by ggodlewski** [comment]
![image](https://github.com/mieweb/wikiGDrive/assets/818238/84456e27-7847-4d2b-8539-7788d7b54ee5)
