### ISSUE TITLE
Navigation page doesn't publish changes to reports

### ISSUE THREAD

**Issue by hammbi** [mieweb/wikiGDrive#425]
FileId: 15ph1CZwQ9C9J0gXCJo1s9JE8ApXfFct4w2RJoDqRvz4
URL: https://wikigdrive.com/drive/0AF_nrE0_QH_2Uk9PVA/content/navigation.md#html
Google Docs: https://drive.google.com/open?id=15ph1CZwQ9C9J0gXCJo1s9JE8ApXfFct4w2RJoDqRvz4

![image](https://github.com/mieweb/wikiGDrive/assets/22618820/495849a9-ed9d-493c-9f15-3a72103104e1)

**Comment by horner** [comment]
We need to commit the manually config/menu.json

Greg will think on how we will auto-commit it when the navigation.md is committed.
