### ISSUE TITLE
Git commit failed

### ISSUE THREAD

**Issue by auhrick** [mieweb/wikiGDrive#438]
### Issue

I am not able to publish the "Interface Specifications" document upon making updates to the document.

### Steps to recreate issue

1. make update to document
2. Sync
3. Upon syncing, the Commit box displays, but it displays "Bridget Hamm updated Interface Specification". I am not Bridget Hamm, however, Bridget was the last person to make updates and commit them. This box is usually blank and does not contain any text by default.
![image](https://github.com/mieweb/wikiGDrive/assets/102048851/bdaedeb5-e10b-4caa-8e14-45edafe354a3)
4. I delete the text in the commit box and type my own commit note "Add Nevada State Immunization Registry Interface" and click "commit and push"
5. I see message the sync and transform is done, but then I get "Git commit failed" message. Along with that, the commit box now says "Alice Uhrick updated Interface Specification". I am not used to seeing the commit box after clicking the "commit and push" button, so it is unusual now that is displays the text that I updated it.
![image](https://github.com/mieweb/wikiGDrive/assets/102048851/ad6d3ad7-4139-401f-9e5c-5d6de146acd0)

I did click on the View log link and this is what displays:
I attempted to publish twice. The second attempt log file link is below.
https://wikigdrive.com/drive/0AF_nrE0_QH_2Uk9PVA#drive_logs:job-661178e7-4468-4d7a-bdf2-567a2134fab6 
![image](https://github.com/mieweb/wikiGDrive/assets/102048851/d2072cb7-11ac-421c-813d-dd695b875c7b)

Additional Note:
For some reason I see "Auto commit for file version change" after I tried to commit and push. I don't know what that is all about or what it is doing, but I think my actions triggered it.
![image](https://github.com/mieweb/wikiGDrive/assets/102048851/416ffc12-478a-4fca-85f4-1b34360849d4)
![image](https://github.com/mieweb/wikiGDrive/assets/102048851/8f3834ef-3055-4b82-bdcc-c8d46ad53f19)

**Comment by ggodlewski** [comment]
@horner it was fixed in https://github.com/mieweb/wikiGDrive/pull/437/commits/df0522b4881c72c35da1a33be69785092838a63e I need your review approval to do the deploy.
