### ISSUE TITLE
Deleted links on the Navigation page still display in the Nav sidemenu

### ISSUE THREAD

**Issue by hammbi** [mieweb/wikiGDrive#444]
**Describe the bug**
When you go to the navigation page (https://docs.google.com/document/d/15ph1CZwQ9C9J0gXCJo1s9JE8ApXfFct4w2RJoDqRvz4/edit) and delete a link it does not remove the link from the Nav sidemenu (even after publishing changes to the Navigation page).

**To Reproduce**
The link under Functions->E-Chart called Quick View - Meaningful Use Portlet was deleted from the Navigation page (https://docs.google.com/document/d/15ph1CZwQ9C9J0gXCJo1s9JE8ApXfFct4w2RJoDqRvz4/edit).
![image](https://github.com/mieweb/wikiGDrive/assets/22618820/a2e69f44-5e8c-460b-b34d-ec70234c7d56)

When I go to https://docs.enterprisehealth.com/functions/e-chart/ the Quick View - Meaningful Use Portlet still displays in the Nav sidemenu
![image](https://github.com/mieweb/wikiGDrive/assets/22618820/828f78be-3f70-40e1-9164-08e96d75f217)

The Quick View - Meaningful Use Portlet also displays when you click the E-Chart page, although there doesn't appear to be a way to remove it from that page
![image](https://github.com/mieweb/wikiGDrive/assets/22618820/c32cadd4-84b7-4cee-b5b0-541528d3b871)

**Comment by horner** [comment]
@ggodlewski they found this issue

**Comment by hammbi** [comment]
@ggodlewski Is this solved in the new PR because the one from Mar 9th did not solve the issue?

**Comment by ggodlewski** [comment]
The https://github.com/mieweb/docs/pull/25 is still open. I have a meeting with @horner on Monday. We'll talk about it.

**Comment by horner** [comment]
we put the "temporary" fix in docs repo.

**Comment by horner** [comment]
This appears fixed:

<img width="900" alt="image" src="https://github.com/mieweb/wikiGDrive/assets/6094599/5d176c0d-f60c-41e6-a17f-d88ae41b76b7">
