### ISSUE TITLE
Unable to Publish

### ISSUE THREAD

**Issue by auhrick** [mieweb/wikiGDrive#450]
### Issue:

I am trying to publish "HL7 Segment Definitions" google doc and am getting an error "Action Failed"
Error Log URL" https://docs.google.com/document/d/1UOWa1lEWNqb3lpaVgtPcU0rmNo5O_v_2udjcqVgZt80/edit 

![image](https://github.com/mieweb/wikiGDrive/assets/102048851/90c8c19f-1342-46b1-b709-4ddb2bfdf624)
![image](https://github.com/mieweb/wikiGDrive/assets/102048851/d7c25c87-62ac-4eac-9e37-56c3ec8f0aaa)

**Comment by ggodlewski** [comment]
```
Error: error building site: assemble: "/site/content/functions/system-administration/system-controls/merging-accounts-charts-in-system.md:54:1": failed to extract shortcode: shortcode "info" must be closed or self-closed
```

So, in https://docs.google.com/document/d/1c8cCEVXofjXUudcZMlnClVF1Ocn4JL3jIHFRSujRDoY/edit There is `{{% info %}}` which is not closed by `{{% /info %}}`.

**Comment by horner** [comment]
<img width="1306" alt="Screenshot 2024-03-23 at 8 23 05 AM" src="https://github.com/mieweb/wikiGDrive/assets/6094599/d31375e0-1487-45a6-a966-d3cab05078d9">

**Comment by horner** [comment]
Also this one 
<img width="1099" alt="image" src="https://github.com/mieweb/wikiGDrive/assets/6094599/539106b6-e7e1-4ac9-a6b1-076347168749">

**Comment by horner** [comment]
Fixed the two documents.  It's working now.  Greg will track making these errors more clear to the end-user in #451
