### ISSUE TITLE
Fix commit all

### ISSUE THREAD

**Issue by ggodlewski** [mieweb/wikiGDrive#487]

**Comment by ggodlewski** [comment]
Sometimes commit box is missing despite selecting all the files

![Image](https://github.com/user-attachments/assets/7e817a33-4597-4754-8029-dd8f1183c788)

**Comment by monpie3** [comment]
Not sure if it's related but when I was playing with my Training drive, I was able to check more files than were available. The last 10 seconds of this video illustrates it better. I don't know exactly what triggers it, I was just refreshing the page

https://github.com/user-attachments/assets/4348374e-ea1d-41ae-9789-adc2ed61679d

**Comment by ggodlewski** [comment]
Unable to reproduce

- I don't know which drive is it
- I can't see the url bar while refreshing

**Comment by monpie3** [comment]
https://wikigdrive.com/drive/0AKUxNUHedn4hUk9PVA/config/_defaultmenu.en.json#git_commit sorry! I was testing it here

**Comment by ggodlewski** [comment]
Should work after prod deployment.
