### ISSUE TITLE
Server dying for some reason

### ISSUE THREAD

**Issue by ggodlewski** [mieweb/wikiGDrive#517]
Sometimes I'm getting:

![image](https://github.com/user-attachments/assets/4bbca9c0-f2d3-4175-838f-3184f335f090)

and I'm unable to ssh into it.

For example right now: Sun Nov 24 17:38:25 2024 UTC

**Comment by ggodlewski** [comment]
@monpie3 I'm unable to ssh into dev server, can you contact someone who has access?

**Comment by monpie3** [comment]
@ggodlewski  can we close it?

**Comment by ggodlewski** [comment]
@monpie3 still in progress.

**Comment by ggodlewski** [comment]
This should be solved by https://github.com/mieweb/wikiGDrive/pull/514

Also big performance boost:

![image](https://github.com/user-attachments/assets/96734fde-8c7d-4988-8a2c-6408be8170cb)

![image](https://github.com/user-attachments/assets/d027ddf0-64a2-4cdb-838e-f5ebca8a1a5b)

**Comment by ggodlewski** [comment]
@horner we have same issue today https://github.com/mieweb/wikiGDrive/actions/runs/12299851147/job/34326799342

![image](https://github.com/user-attachments/assets/af36b190-66a4-42b4-8f36-f6462caa3a1f)
