### ISSUE TITLE
Github runner not picking up job

### ISSUE THREAD

**Issue by ggodlewski** [mieweb/wikiGDrive#518]
https://github.com/mieweb/wikiGDrive/actions/runs/12054164384/job/33615424903

![image](https://github.com/user-attachments/assets/f46ea56b-275d-4675-97ec-3f205c9c8060)

![image](https://github.com/user-attachments/assets/1cb8dd33-5d79-4e3a-ba9f-cdfb4ec24844)

**Comment by ggodlewski** [comment]
In the runners I only have wgd-prod.
wgd-dev is missing

![image](https://github.com/user-attachments/assets/5f5b330a-091f-43c0-82ee-13f9dbf476ef)

**Comment by ggodlewski** [comment]
I don't have access to the settings: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/adding-self-hosted-runners#adding-a-self-hosted-runner-to-a-repository

**Comment by horner** [comment]
fixed!
