### ISSUE TITLE
Incorrect file name in git commit

### ISSUE THREAD

**Issue by ggodlewski** [mieweb/wikiGDrive#522]
FileId: 1iP-ySrieQYcyPJLhyz5Z4wvNGROZxWOGK74JTokM2IQ
URL: https://pr-514.wikigdrive.com/drive/0AKUxNUHedn4hUk9PVA/another-file.md#html
Google Docs: https://drive.google.com/open?id=1iP-ySrieQYcyPJLhyz5Z4wvNGROZxWOGK74JTokM2IQ

![image](https://github.com/user-attachments/assets/59199a1c-1945-47d7-8603-70d55476d215)

It should be `another-file.md` not `test-file.md` on the left side

**Comment by monpie3** [comment]
note: it isn't bug on prod, it's for https://github.com/mieweb/wikiGDrive/pull/514

**Comment by monpie3** [comment]
I tested PR-514, and it looks like all critical functionalities work properly.
