### ISSUE TITLE
Remote branch set up is ignored 

### ISSUE THREAD

**Issue by pierzchala-m** [mieweb/wikiGDrive#525]
Even though the remote branch is set to master, it tries to push to main (which does not exist).

![image](https://github.com/user-attachments/assets/1e6ab321-368c-4773-b0d4-1edcd1d55f3c)

![image](https://github.com/user-attachments/assets/e9834e96-0f38-4207-a5f9-4d17f6a51e1e)

![image](https://github.com/user-attachments/assets/c9463bee-eae8-4ad9-91c5-d36bc9b79af7)

Target repo: https://github.com/pierzchala-m/training

**Comment by ggodlewski** [comment]
I added option `git branch -m` to rename local branch as a fix.

![image](https://github.com/user-attachments/assets/cb1c1fc4-937f-4ef8-aba8-bc50221bf198)

In longer term I think we need a better git interface, but it's something to design, a complete subproject.
