### ISSUE TITLE
Wikigdrive service account shows no error if the is no permission to the folder

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#60]
wikigdrive "https://drive.google.com/drive/folders/0AB1bEyFsoJ9pUk9PVA" --service_account=wikigdrive.json --dest example --link_mode uglyURLs --without-folder-structure
Listening folder: /
Finished

**Comment by ggodlewski** [comment]
Tried both v2 and v3 APIs. All methods returns empty list without throwing an error for service account. At the moment I can't find solution.

**Comment by horner** [comment]
Thanks for checking.  I will update the documentation with an alert.
