### ISSUE TITLE
Add support for Hexo as an output format

### ISSUE THREAD

**Issue by wreiske** [mieweb/wikiGDrive#77]
After completing https://github.com/mieweb/wikiGDrive/issues/76 please add support for Hexo as an output format.

**Comment by horner** [comment]
Why Hexo? Hugo faster.

**Comment by wreiske** [comment]
> Hexo

![image](https://user-images.githubusercontent.com/6295044/90646497-43e4bf80-e205-11ea-97e2-1f43b1466d7c.png)

We should support more than just Hugo as an output format. After talking with Greg, it's not too hard to get more than just hugo as an output format. It may make wikiGDrive more attractive if we can easily allow different output formats.
