### ISSUE TITLE
Bold text not transforming with watch

### ISSUE THREAD

**Issue by wreiske** [mieweb/wikiGDrive#84]
While using watch, it doesn't look like bold text is transforming correctly.

![image](https://user-images.githubusercontent.com/6295044/92036030-9feb3000-ed3d-11ea-92d7-e1e2efd58115.png)

![image](https://user-images.githubusercontent.com/6295044/92035985-8f3aba00-ed3d-11ea-9d87-cd458878a461.png)

**Comment by ggodlewski** [comment]
This is a way hugo handles the markdown. If place space between `**` and text if will not be transformed into bold.
Remove the space and try again.

**Comment by wreiske** [comment]
We need to be able to support bolded text following a period. Oh, you're saying the space after the period is possibly bolded? I will check.

**Comment by wreiske** [comment]
Yes, after checking the space after the period was bolded.
